//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbCms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_file_infos
    {
        public decimal file_info_id { get; set; }
        public long contents_id { get; set; }
        public string kind { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public Nullable<short> paper_size_id { get; set; }
        public string delete_state { get; set; }
        public string create_function { get; set; }
        public System.DateTime create_date_time { get; set; }
        public int create_user { get; set; }
        public string update_function { get; set; }
        public Nullable<System.DateTime> update_date_time { get; set; }
        public Nullable<int> update_system_user { get; set; }
        public string delete_function { get; set; }
        public Nullable<System.DateTime> delete_date_time { get; set; }
        public Nullable<int> delete_system_user { get; set; }
    }
}
