//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbCms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TbCmsContext : DbContext
    {
        public TbCmsContext()
            : base("name=TbCmsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<l_download> l_download { get; set; }
        public virtual DbSet<m_businesses> m_businesses { get; set; }
        public virtual DbSet<m_categories> m_categories { get; set; }
        public virtual DbSet<m_creators> m_creators { get; set; }
        public virtual DbSet<m_file_kinds> m_file_kinds { get; set; }
        public virtual DbSet<m_keywords> m_keywords { get; set; }
        public virtual DbSet<m_menus> m_menus { get; set; }
        public virtual DbSet<m_news_elements> m_news_elements { get; set; }
        public virtual DbSet<m_occupations> m_occupations { get; set; }
        public virtual DbSet<m_paper_makers> m_paper_makers { get; set; }
        public virtual DbSet<m_paper_sizes> m_paper_sizes { get; set; }
        public virtual DbSet<m_papers> m_papers { get; set; }
        public virtual DbSet<m_permissions> m_permissions { get; set; }
        public virtual DbSet<m_roles> m_roles { get; set; }
        public virtual DbSet<m_system_users> m_system_users { get; set; }
        public virtual DbSet<m_tags> m_tags { get; set; }
        public virtual DbSet<t_category_files> t_category_files { get; set; }
        public virtual DbSet<t_category_tags> t_category_tags { get; set; }
        public virtual DbSet<t_contents> t_contents { get; set; }
        public virtual DbSet<t_contents_files> t_contents_files { get; set; }
        public virtual DbSet<t_contents_info_tags> t_contents_info_tags { get; set; }
        public virtual DbSet<t_contents_infos> t_contents_infos { get; set; }
        public virtual DbSet<t_contents_reviews> t_contents_reviews { get; set; }
        public virtual DbSet<t_file_infos> t_file_infos { get; set; }
        public virtual DbSet<t_files> t_files { get; set; }
        public virtual DbSet<t_news> t_news { get; set; }
        public virtual DbSet<t_news_add_element_tags> t_news_add_element_tags { get; set; }
        public virtual DbSet<t_news_add_elements> t_news_add_elements { get; set; }
        public virtual DbSet<t_news_add_files> t_news_add_files { get; set; }
        public virtual DbSet<t_news_files> t_news_files { get; set; }
        public virtual DbSet<t_news_tags> t_news_tags { get; set; }
        public virtual DbSet<t_paper_size_papers> t_paper_size_papers { get; set; }
        public virtual DbSet<m_permission_kinds> m_permission_kinds { get; set; }
    }
}
